### ISSUE TITLE
Self-defined function handler cannot work

### ISSUE THREAD

**Issue by LittleNewton** [fuzzware-fuzzer/fuzzware-emulator#12]
Hi there!

```yaml
  # Handle with a high-level handler
  # For an extensive use of such handlers, see https://github.com/ucsb-seclab/hal-fuzz
  # WARNING: if used in fuzzing, Python-based handlers slow down fuzzing a lot
  puts:
    handler: fuzzware_harness.user_hooks.generic.stdio.puts
    # Still execute the original firmware function (defaults to True)
    do_return: False

  # Native hooks leading to binary patches
  # Return 0
  my_useless_initialization_function_requiring_zero:
    # BEWARE: this requires 8 bytes of function body
    handler: native.return_0x0
  # Return 1
  my_useless_initialization_function_requiring_nonzero:
    # BEWARE: this requires 8 bytes of function body
    handler: native.return_0x1
  # And welcome to the dark side...
  my_useless_initialization_function_requiring_binary_patch:
    # manually patching "bx lr" as byte patch
    handler: native.inline_asm_7047
```

The above shows custom handlers provided in [`README_config.yml`](https://github.com/fuzzware-fuzzer/fuzzware-emulator/blob/main/README_config.yml). I attempted to implement time marking through a `main` handler:

``` python
# filename: /home/user/fuzzware/emulator/harness/fuzzware_harness/user_hooks/generic/my_handler.py

from unicorn import *
from unicorn.arm_const import * 

def log_main_hit_time(uc):
    MAIN_ADDR = 0x8004192 # This is the main function address
    
    pc = uc.reg_read(UC_ARM_REG_PC)
    
    if pc == MAIN_ADDR:
        from datetime import datetime
        with open('/firmware_db/function_hit.txt', 'a') as f:
            f.write(f"main hit: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} PC:{hex(pc)}\n")
        uc.emu_stop()
```

**I aim to measure the time spent from `Reset_Handler` to `main`.**

However, this handler is triggered in the first second and continues to execute **repeatedly**, generating a file tens of megabytes in size. Ideally, this file should contain only a single record. **I can not figure out if is it a feature or a bug.**

Here’s everything needed - the binary firmware and Fuzzware config/sym are all in the attachment [👉 firmware_sample.zip](https://github.com/user-attachments/files/17670790/firmware_sample.zip).
